website/models.py
from enum import unique
from os import name
from peewee import *
import datetime
from flask_login import UserMixin

# The database for the entire project is created here. It needs to be created before
# the models can be created. However, it does NOT need to be connected to here. This is
# simply a staging ground.

db = SqliteDatabase("test.db")


# Basemodel from PeeWee helps us establish our own tables.

class BaseModel(Model):
    class Meta:
        database = db

class User(BaseModel, UserMixin):
    id = PrimaryKeyField()
    email = CharField(unique=True)
    username = CharField(unique = True)
    password = CharField()
    cash_on_hand = IntegerField (default = 150000)

class Horse(BaseModel):
    name = CharField(unique=True)
    gender = CharField()
    timestamp = DateTimeField(default=datetime.datetime.now)

    
#Only drive the program if we run from this module.
    
if __name__ == "__main__":
    db.connect()
    print("Running from models.py ...")
    User.drop_table()
    Horse.drop_table()

website/__init__.py
from flask import Flask, redirect, render_template
from .models import Horse, db, User
from flask_login import LoginManager



def create_app():
   app = Flask(__name__)

   app.config["SECRET_KEY"] = "helloworld"

    # database initialized and created in one move upon app creaton.
   with app.app_context():
       db.init("test.db")
       User.create_table()
       Horse.create_table()

   from . import auth
   from . import views  

   app.register_blueprint(auth.auth)
   app.register_blueprint(views.views)
   
   login_manager = LoginManager()
   login_manager.login_view = "auth.login"
   login_manager.init_app(app)
   
   # Uses a Session to store the given the ID of a user.
   @login_manager.user_loader
   def load_user(id):
    try:
        return User.get(User.id == int(id))
    except User.DoesNotExist:
        return None

#Return the entire app.
   return app

website/auth.py
# basic Flask functionality

import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

#necessary database imports, from init and models.py
from . import db
from .models import User

# user session modules
from flask_login import login_user, logout_user, login_required, current_user, LoginManager

# password hashing and checking modules
from werkzeug.security import check_password_hash, generate_password_hash

auth = Blueprint('auth', __name__)



# Either allow user to log in via a POST method, or present the login page.

@auth.route("/login", methods=["POST", "GET"])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.get(User.email == email)
        
        if user:

            # Compare hashed password. If it's a match, log the user in and return them to the home page.
            if check_password_hash(user.password, password):
                flash("Logged in!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Password is incorrect.", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login.html", user=current_user)

#Create a new user with this route.
@auth.route("/sign_up", methods=["POST", "GET"])
def sign_up():

    #Routes essentially "work backwards."
    #If someone POST at the sign-up page, AKA tries
    # to make a new account, we check to  see if they already exist.
    # If not, we make a new user.

    #If the person simply loads the page, we present the page.

    if request.method == "POST":

        #Get submitted data from form.

        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        #Query the database for the email and the username, since these must be unique.

        try:
            # Query the database for the email (assuming email is unique)
            email_exists = User.get(User.email == email)
        except User.DoesNotExist:
            email_exists = None

        try:
            # Query the database for the username (assuming username is unique)
            username_exists = User.get(User.username == username)
        except User.DoesNotExist:
            username_exists = None



        if email_exists:
            flash("This email is already in use.", category="error")
        elif username_exists:
            flash("This username is already in use.", category="error")

        # If the email or username are already in use, deny account creation.

        elif password1 != password2:
            flash("Passwords don't match!", category="error")

        # If the password is in use, deny account creation.

        elif len(username) < 2:
            flash("Your username is too short.")
        elif len(password1) < 6:
            flash("Password is too short.", category="error")
        elif len(email) < 4:
            flash("Email is invalid.", category = "error")

        # If all conditions are met, then create a new user.
        else:
            # The password MUST be hashed.
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method="pbkdf2:sha256"))
            new_user.save()
            
            login_user(new_user, remember=True)

            # Log the new user in automatically.          
        
            flash("User created!", "message")

            # And send them back to the home page.
            return redirect(url_for("views.home"))

    return render_template("register_page.html", user=current_user)

#Simple logout and return to home.
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/views.py
from os import name
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from flask_login import login_required, current_user

# Naming our main blueprint "views".

views = Blueprint ('views', __name__)

@views.route("/", methods=["POST", "GET"])
@login_required
def home():
    if request.method == "POST":

        email = request.form['email']

        from website import db
        from .models import User
        db.connect()
        User.create_table()
        
    
        User.create(email=email)

        db.commit()
        return "Thanks!"

        
    else:
        return render_template("home.html", user = current_user)   

@views.route("/user_search", methods=["POST", "GET"])
def user_lookup_page():
    if request.method == "POST":

        user_id = request.form['user_id']

        return redirect ( url_for ("views.user_lookup_result", user_id = user_id))
    else:
        return render_template("user_lookup.html")

# This view is the result page of the search view accessed above. The view above passes along the user's entry as user_id 
# and if a result is present, it will render in the template below.
    
@views.get('/users/<int:user_id>')
def user_lookup_result(user_id):
    from website import db
    from .models import User
    db.connect()
    # new user variable accesses the table with User.select()
    user = User.select().where(User.id == user_id).get()
    print(f"{user} is the number just entered!!!")

    return render_template("user_lookup_results.html", user = user )
    

@views.route('/submit_horse', methods=["POST", "GET"])
def submit_horse():
    if request.method == "POST":
        horse_Name = request.form["horse_Name"]
        horse_Gender = request.form["horse_Gender"]

        from website import db
        from .models import Horse
        db.connect()
        Horse.create_table()
        
    
        Horse.create(name=horse_Name, gender = horse_Gender)

        db.commit()

        flash('You successfully submitted a horse!', "message")

        return render_template("submit_horse.html")     
    else:    
        return render_template("submit_horse.html")

@views.route("/horse_table")

def horse_table():
    from website import db
    from .models import Horse
    db.connect()
    # new user variable accesses the table with User.select()
    horses = Horse.select()

    for horse in horses:
        print(horse)

    return render_template("horse_table.html", horses = horses )

@views.route("/claim_horse/<horse_name>", methods=["POST", "GET"])

def claim_horse(horse_name):
    from website import db
    from .models import Horse
    db.connect()

    # Use .get() instead of .select().where() if you expect only one result
    db_horse = Horse.get(Horse.name == horse_name)

    # Access the 'name' attribute of the retrieved Horse object
    return f"Hi!, {db_horse.name}"

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Cashew Butter {% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                
                {% if user %}
                    {% if user.is_authenticated %}

                    <a class="nav-item nav-link" href="{{ url_for('views.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        

                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                
                {% endif %}
                {% endif %}
    
                
                <a class="nav-item nav-link" href="{{ url_for('views.user_lookup_page') }}">User Lookup 🔍 </a>
                <a class="nav-item nav-link" href="{{ url_for('views.submit_horse') }}">Submit Horse 🐎</a>
                <a class="nav-item nav-link" href="{{ url_for('views.horse_table') }}">Horse Table 💻 </a>
            </div>
        </div>
    </div>

</nav>

<!-- {% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for category, message in messages %}
{% if category == "error" %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message}}
    <button
            type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
{% else %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message}}
    <button
            type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>

{% endif %}
{% endfor %}
{% endif %}
{% endwith %} -->

<div class="container">
<br> <br> <br>
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

website/templates/home.html
{%extends "base.html "%} 

{% block content %}
<br />

{% with messages = get_flashed_messages() %}
{% for message in messages %}
{{  message  }}
{% endfor %}
{% endwith %}

<h1 align="center"><u>Cashew Butter</u> 🏇🏾 </h1>

<h4 align="center"> A Horse Racing Ownership Simulation Experience.</h4>

<form method="POST">
  <div class="form-group">
    <label for="email">Email.</label>
    <input
      type="text"
      id="email"
      name="email"
      class="form-control"
      placeholder="Enter Email"
    />

    <br />
    <div align="center">
      <button class="btn btn-primary" type="submit">Sign Up</button>
    </div>
  </div>
</form>
{% endblock %}

website/templates/horse_table.html
{%extends "base.html "%} {% block title %}Horse Table Lookup{% endblock %} 

{% block content %}
<h2 align="center"> <u>Available horses<u> </h2>
<table class="table table-striped">
    <thead>
    <tr>
      <th scope="col"><h2><u>Horse</u></h2></th>
      <th scope="col"><h2><u>Gender</u></h2></th>
      <th scope="col"> <h2><u>Time Created</u></h2></th>
    </tr>
  </thead>

  <tbody>   
    {% for horse in horses %}
    <tr>
        <th scope="row">{{ horse.name }}</th>
        <td> {{ horse.gender }} </td>
        <td> {{ horse.timestamp }} </td>
        <td>
          <!-- Add a Bootstrap button (btn class) with a link or any action you want -->
          <a href="{{ url_for('views.claim_horse', horse_name=horse.name) }}" class="btn btn-primary" method="POST">Action</a>

        </td>
      </tr>  
    {% endfor %}  
  </tbody>
</table>

{% endblock %}

website/templates/login.html
{%extends "base.html "%}

{% block title %}Home{% endblock %}
{% block content %}
<p>Welcome to my app.</p>

<form method="POST">
    <h3 align="center">Login</h3>


    <div class="form-group">
        <label for = "email"> Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email"/>
        <label for = "password"> Password </label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Enter Password"/>
        <br>
        <div align = "center">
        <button class ="btn btn-primary" type="submit">Login</button>
        </div>
    </div>

</form>

{% endblock %}

website/templates/register_page.html
{%extends "base.html "%} {% block title %}Submit a horse name{% endblock %} 

{% block content %}
{# Obtain a list of messages if flashes were generated. #}
{% with messages = get_flashed_messages() %}
  {% if messages %} {# If messages exist... #}
    <ul class=flashes>
    {% for message in messages %} {# Simply post them all the same way. #}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message}}
        <button
                type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<div align="center">
    <form method = "POST">
        <h3>
            <label for="email">  Enter an email:    </label>
        </h3>

    <div align="center">
    <input type="text" name="email" id="email"/>
    <br> <br> <br> <br>

    <label for="username">Enter a username:</label>
    <input type="text" name="username" id="username"/>

    <label for="password1">Enter password:</label>
    <input type="text" name="password1" id="password1"/>

    <br>

    <label for="password2">Enter password again:</label>
    <input type="text" name="password2" id="password2"/>
    

    <br>
    
    </div>

    <button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>

{% endblock %}

website/templates/sign_up.html
{%extends "base.html "%}

{% block title %}Sign Up{% endblock %}
{% block content %}
<br>

<form method="POST">
    <h3 align="center">Sign Up for Cashew Butter :) </h3>


    <div class="form-group">
        <label for="email"> Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email"/>

        <label for="username"> Username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Enter Username"/>

        <label for="password1"> Password </label>
        <input type="password" id="password1" name="password1" class="form-control" placeholder="Enter Password"/>

        <label for="password2"> Password </label>
        <input type="password" id="password2" name="password2" class="form-control" placeholder="Enter Password Again"/>

        <br>
        <div align="center">
            <button class="btn btn-primary" type="submit">Sign Up</button>
        </div>
    </div>

</form>

{% endblock %}

website/templates/submit_horse.html
{%extends "base.html "%} {% block title %}Submit a horse name{% endblock %} 

{% block content %}
{# Obtain a list of messages if flashes were generated. #}
{% with messages = get_flashed_messages() %}
  {% if messages %} {# If messages exist... #}
    <ul class=flashes>
    {% for message in messages %} {# Simply post them all the same way. #}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message}}
        <button
                type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<div align="center">
    <form method = "POST">
        <h3>
            <label for="horse_Name">  Enter a Horse Name:    </label>
        </h3>

    <input type="text" name="horse_Name" id="horse_Name"/>
    <br> <br> <br> <br>    
    <label for="horse_Gender">Select Horse Gender:</label>
    <select id="horse_Gender" name="horse_Gender">
        <option value="Stallion">Stallion</option>
        <option value="Mare"> Mare </option>
        <option value="Gelding"> Gelding </option>
        <option value="Colt"> Colt </option>
        <option value="Filly"> Filly </option>

    </select>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>

{% endblock %}

website/templates/user_lookup.html
{%extends "base.html "%} {% block title %}User Lookup{% endblock %} 

{% block content %}
<form method="POST">
    <div class="form-group">
      <label for="user_id">User Id number.</label>
      <input
        type="text"
        id="user_id"
        name="user_id"
        class="form-control"
        placeholder="Enter A Number"
      />
  
      <br />
      <div align="center">
        <button class="btn btn-primary" type="submit">Search</button>
      </div>
    </div>
  </form>
{% endblock %}

website/templates/user_lookup_results.html
{%extends "base.html "%} 

{% block title %} User Lookup {% endblock %} 

{% block content %}

    <h6> Email: </h6>
    <p> {{ user.email }} </p>

    <h6> Cash on Hand: </h6>
    {{ user.cash_on_hand }}

    <h6>  </h6>

{% endblock %}